export const types = {
  INCREASE_TODO_DATA: 'INCREASE_TODO_DATA',
  DECREASE_TODO_DATA: 'DECREASE_TODO_DATA',
  INCREASE_TODO_DATA_START: 'INCREASE_TODO_DATA_START',
  INCREASE_TODO_DATA_END: 'INCREASE_TODO_DATA_END'
}